using DAL.Repository;
using DAL.UnitOfWork;
using Domain.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace DAL.Seed
{
    public class SeedData
    {
        private readonly RoleManager<Role> _roleManager;
        private readonly UserManager<User> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IRepository<PermissionType> _PermissionTypeRepository;
        private readonly IRepository<il> _ilRepository;
        private readonly IRepository<ilce> _ilceRepository;
        private readonly IRepository<WorksiteWorkerType> _WorksiteWorkerTypeRepository;
        private readonly IRepository<WorksiteActionType> _WorksiteActionTypeRepository;
        private readonly IRepository<Year> _YearRepository;
        private readonly IRepository<Month> _MonthRepository;



        public SeedData(RoleManager<Role> roleManager, UserManager<User> userManager, IUnitOfWork unitOfWork)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _unitOfWork = unitOfWork;
            _PermissionTypeRepository = _unitOfWork.GetRepository<PermissionType>();
            _ilRepository = _unitOfWork.GetRepository<il>();
            _ilceRepository = _unitOfWork.GetRepository<ilce>();
            _WorksiteWorkerTypeRepository = _unitOfWork.GetRepository<WorksiteWorkerType>();
            _WorksiteActionTypeRepository = _unitOfWork.GetRepository<WorksiteActionType>();
            _YearRepository = _unitOfWork.GetRepository<Year>();
            _MonthRepository = _unitOfWork.GetRepository<Month>();
        }
        public async Task SeedAsync()
        {
            await SeedRolesAndUsersAsync();
            await SeedPermissionsAsync();
            await SeedililceAsync();
            await SeedWorksiteWorkerTypesAsync();
            await SeedWorksiteActionTypesAsync();
            await SeedYearMonthAsync();
        }
        public async Task SeedRolesAndUsersAsync()
        {
            try
            {
                // Check if the database has already been seeded
                if (!(await _roleManager.Roles.AnyAsync()))
                {
                    // Create roles
                    await _roleManager.CreateAsync(new Role("Admin"));
                    await _roleManager.CreateAsync(new Role("User"));
                }
                if (!(await _userManager.Users.AnyAsync()))
                {
                    // Create users
                    var adminUser = new User
                    {
                        UserName = "admin@example.com1",
                        Email = "admin@example.com"
                    };

                    var userUser = new User
                    {
                        UserName = "user@example.com",
                        Email = "user@example.com"
                    };

                    // Add users to the appropriate roles
                    await _userManager.CreateAsync(adminUser, "P@ssw0rd");
                    await _userManager.AddToRoleAsync(adminUser, "Admin");

                    await _userManager.CreateAsync(userUser, "P@ssw0rd");
                    await _userManager.AddToRoleAsync(userUser, "User");

                }
            }
            catch (Exception ex)
            {
                // Log any exceptions that occur during the seeding process
                Console.WriteLine(ex.Message);
            }
        }
        public async Task SeedPermissionsAsync()
        {
            try
            {
                if ((await _PermissionTypeRepository.GetAllAsync()).Count == 0)
                {
                    var permissonType = new PermissionType() { Name = "Annual Leave" };
                    await _PermissionTypeRepository.AddAsync(permissonType);
                    await _unitOfWork.CommitAsync();
                }

            }
            catch (Exception ex)
            {
                // Log any exceptions that occur during the seeding process
                Console.WriteLine(ex.Message);
            }
        }
        public async Task SeedililceAsync()
        {
            try
            {
                if ((await _ilRepository.GetAllAsync()).Count == 0)
                {
                    var ils = new List<il>() {
                            new il() {Id = 1 , Name = "Adana"},
                            new il() {Id = 2 , Name = "Adıyaman"},
                            new il() {Id = 3 , Name = "Afyon"},
                            new il() {Id = 4 , Name = "Ağrı"},
                            new il() {Id = 5 , Name = "Amasya"},
                            new il() {Id = 6 , Name = "Ankara"},
                            new il() {Id = 7 , Name = "Antalya"},
                            new il() {Id = 8 , Name = "Artvin"},
                            new il() {Id = 9 , Name = "Aydın"},
                            new il() {Id = 10 , Name = "Balıkesir"},
                            new il() {Id = 11 , Name = "Bilecik"},
                            new il() {Id = 12 , Name = "Bingöl"},
                            new il() {Id = 13 , Name = "Bitlis"},
                            new il() {Id = 14 , Name = "Bolu"},
                            new il() {Id = 15 , Name = "Burdur"},
                            new il() {Id = 16 , Name = "Bursa"},
                            new il() {Id = 17 , Name = "Çanakkale"},
                            new il() {Id = 18 , Name = "Çankırı"},
                            new il() {Id = 19 , Name = "Çorum"},
                            new il() {Id = 20 , Name = "Denizli"},
                            new il() {Id = 21 , Name = "Diyarbakır"},
                            new il() {Id = 22 , Name = "Edirne"},
                            new il() {Id = 23 , Name = "Elazığ"},
                            new il() {Id = 24 , Name = "Erzincan"},
                            new il() {Id = 25 , Name = "Erzurum"},
                            new il() {Id = 26 , Name = "Eskişehir"},
                            new il() {Id = 27 , Name = "Gaziantep"},
                            new il() {Id = 28 , Name = "Giresun"},
                            new il() {Id = 29 , Name = "Gümüşhane"},
                            new il() {Id = 30 , Name = "Hakkari"},
                            new il() {Id = 31 , Name = "Hatay"},
                            new il() {Id = 32 , Name = "Isparta"},
                            new il() {Id = 33 , Name = "İçel"},
                            new il() {Id = 34 , Name = "İstanbul"},
                            new il() {Id = 35 , Name = "İzmir"},
                            new il() {Id = 36 , Name = "Kars"},
                            new il() {Id = 37 , Name = "Kastamonu"},
                            new il() {Id = 38 , Name = "Kayseri"},
                            new il() {Id = 39 , Name = "Kırklareli"},
                            new il() {Id = 40 , Name = "Kırşehir"},
                            new il() {Id = 41 , Name = "Kocaeli"},
                            new il() {Id = 42 , Name = "Konya"},
                            new il() {Id = 43 , Name = "Kütahya"},
                            new il() {Id = 44 , Name = "Malatya"},
                            new il() {Id = 45 , Name = "Manisa"},
                            new il() {Id = 46 , Name = "K.Maraş"},
                            new il() {Id = 47 , Name = "Mardin"},
                            new il() {Id = 48 , Name = "Muğla"},
                            new il() {Id = 49 , Name = "Muş"},
                            new il() {Id = 50 , Name = "Nevşehir"},
                            new il() {Id = 51 , Name = "Niğde"},
                            new il() {Id = 52 , Name = "Ordu"},
                            new il() {Id = 53 , Name = "Rize"},
                            new il() {Id = 54 , Name = "Sakarya"},
                            new il() {Id = 55 , Name = "Samsun"},
                            new il() {Id = 56 , Name = "Siirt"},
                            new il() {Id = 57 , Name = "Sinop"},
                            new il() {Id = 58 , Name = "Sivas"},
                            new il() {Id = 59 , Name = "Tekirdağ"},
                            new il() {Id = 60 , Name = "Tokat"},
                            new il() {Id = 61 , Name = "Trabzon"},
                            new il() {Id = 62 , Name = "Tunceli"},
                            new il() {Id = 63 , Name = "Şanlıurfa"},
                            new il() {Id = 64 , Name = "Uşak"},
                            new il() {Id = 65 , Name = "Van"},
                            new il() {Id = 66 , Name = "Yozgat"},
                            new il() {Id = 67 , Name = "Zonguldak"},
                            new il() {Id = 68 , Name = "Aksaray"},
                            new il() {Id = 69 , Name = "Bayburt"},
                            new il() {Id = 70 , Name = "Karaman"},
                            new il() {Id = 71 , Name = "Kırıkkale"},
                            new il() {Id = 72 , Name = "Batman"},
                            new il() {Id = 73 , Name = "Şırnak"},
                            new il() {Id = 74 , Name = "Bartın"},
                            new il() {Id = 75 , Name = "Ardahan"},
                            new il() {Id = 76 , Name = "Iğdır"},
                            new il() {Id = 77 , Name = "Yalova"},
                            new il() {Id = 78 , Name = "Karabük"},
                            new il() {Id = 79 , Name = "Kilis"},
                            new il() {Id = 80 , Name = "Osmaniye"},
                            new il() {Id = 81 , Name = "Düzce"}
                        };

                    await _ilRepository.AddRangeAsync(ils);
                    await _unitOfWork.CommitAsync();
                }

                if ((await _ilceRepository.GetAllAsync()).Count == 0)
                {
                    var ilces = new List<ilce>() {
                            new ilce() {Id = 1, Name = "ALADAĞ", ilId = 1},
                            new ilce() {Id = 2, Name = "CEYHAN", ilId = 1},
                            new ilce() {Id = 3, Name = "ÇUKUROVA", ilId = 1},
                            new ilce() {Id = 4, Name = "FEKE", ilId = 1},
                            new ilce() {Id = 5, Name = "İMAMOĞLU", ilId = 1},
                            new ilce() {Id = 6, Name = "KARAİSALI", ilId = 1},
                            new ilce() {Id = 7, Name = "KARATAŞ", ilId = 1},
                            new ilce() {Id = 8, Name = "KOZAN", ilId = 1},
                            new ilce() {Id = 9, Name = "POZANTI", ilId = 1},
                            new ilce() {Id = 10, Name = "SAİMBEYLİ", ilId = 1},
                            new ilce() {Id = 11, Name = "SARIÇAM", ilId = 1},
                            new ilce() {Id = 12, Name = "SEYHAN", ilId = 1},
                            new ilce() {Id = 13, Name = "TUFANBEYLİ", ilId = 1},
                            new ilce() {Id = 14, Name = "YUMURTALIK", ilId = 1},
                            new ilce() {Id = 15, Name = "YÜREĞİR", ilId = 1},
                            new ilce() {Id = 16, Name = "BESNİ", ilId = 2},
                            new ilce() {Id = 17, Name = "ÇELİKHAN", ilId = 2},
                            new ilce() {Id = 18, Name = "GERGER", ilId = 2},
                            new ilce() {Id = 19, Name = "GÖLBAŞI", ilId = 2},
                            new ilce() {Id = 20, Name = "KAHTA", ilId = 2},
                            new ilce() {Id = 21, Name = "MERKEZ", ilId = 2},
                            new ilce() {Id = 22, Name = "SAMSAT", ilId = 2},
                            new ilce() {Id = 23, Name = "SİNCİK", ilId = 2},
                            new ilce() {Id = 24, Name = "TUT", ilId = 2},
                            new ilce() {Id = 25, Name = "BAŞMAKÇI", ilId = 3},
                            new ilce() {Id = 26, Name = "BAYAT", ilId = 3},
                            new ilce() {Id = 27, Name = "BOLVADİN", ilId = 3},
                            new ilce() {Id = 28, Name = "ÇAY", ilId = 3},
                            new ilce() {Id = 29, Name = "ÇOBANLAR", ilId = 3},
                            new ilce() {Id = 30, Name = "DAZKIRI", ilId = 3},
                            new ilce() {Id = 31, Name = "DİNAR", ilId = 3},
                            new ilce() {Id = 32, Name = "EMİRDAĞ", ilId = 3},
                            new ilce() {Id = 33, Name = "EVCİLER", ilId = 3},
                            new ilce() {Id = 34, Name = "HOCALAR", ilId = 3},
                            new ilce() {Id = 35, Name = "İHSANİYE", ilId = 3},
                            new ilce() {Id = 36, Name = "İSCEHİSAR", ilId = 3},
                            new ilce() {Id = 37, Name = "KIZILÖREN", ilId = 3},
                            new ilce() {Id = 38, Name = "MERKEZ", ilId = 3},
                            new ilce() {Id = 39, Name = "SANDIKLI", ilId = 3},
                            new ilce() {Id = 40, Name = "SİNANPAŞA", ilId = 3},
                            new ilce() {Id = 41, Name = "SULTANDAĞI", ilId = 3},
                            new ilce() {Id = 42, Name = "ŞUHUT", ilId = 3},
                            new ilce() {Id = 43, Name = "DİYADİN", ilId = 4},
                            new ilce() {Id = 44, Name = "DOĞUBAYAZIT", ilId = 4},
                            new ilce() {Id = 45, Name = "ELEŞKİRT", ilId = 4},
                            new ilce() {Id = 46, Name = "HAMUR", ilId = 4},
                            new ilce() {Id = 47, Name = "MERKEZ", ilId = 4},
                            new ilce() {Id = 48, Name = "PATNOS", ilId = 4},
                            new ilce() {Id = 49, Name = "TAŞLIÇAY", ilId = 4},
                            new ilce() {Id = 50, Name = "TUTAK", ilId = 4},
                            new ilce() {Id = 51, Name = "AĞAÇÖREN", ilId = 68},
                            new ilce() {Id = 52, Name = "ESKİL", ilId = 68},
                            new ilce() {Id = 53, Name = "GÜLAĞAÇ", ilId = 68},
                            new ilce() {Id = 54, Name = "GÜZELYURT", ilId = 68},
                            new ilce() {Id = 55, Name = "MERKEZ", ilId = 68},
                            new ilce() {Id = 56, Name = "ORTAKÖY", ilId = 68},
                            new ilce() {Id = 57, Name = "SARIYAHŞİ", ilId = 68},
                            new ilce() {Id = 58, Name = "SULTANHANI", ilId = 68},
                            new ilce() {Id = 59, Name = "GÖYNÜCEK", ilId = 5},
                            new ilce() {Id = 60, Name = "GÜMÜŞHACIKÖY", ilId = 5},
                            new ilce() {Id = 61, Name = "HAMAMÖZÜ", ilId = 5},
                            new ilce() {Id = 62, Name = "MERKEZ", ilId = 5},
                            new ilce() {Id = 63, Name = "MERZİFON", ilId = 5},
                            new ilce() {Id = 64, Name = "SULUOVA", ilId = 5},
                            new ilce() {Id = 65, Name = "TAŞOVA", ilId = 5},
                            new ilce() {Id = 66, Name = "AKYURT", ilId = 6},
                            new ilce() {Id = 67, Name = "ALTINDAĞ", ilId = 6},
                            new ilce() {Id = 68, Name = "AYAŞ", ilId = 6},
                            new ilce() {Id = 69, Name = "BALA", ilId = 6},
                            new ilce() {Id = 70, Name = "BEYPAZARI", ilId = 6},
                            new ilce() {Id = 71, Name = "ÇAMLIDERE", ilId = 6},
                            new ilce() {Id = 72, Name = "ÇANKAYA", ilId = 6},
                            new ilce() {Id = 73, Name = "ÇUBUK", ilId = 6},
                            new ilce() {Id = 74, Name = "ELMADAĞ", ilId = 6},
                            new ilce() {Id = 75, Name = "ETİMESGUT", ilId = 6},
                            new ilce() {Id = 76, Name = "EVREN", ilId = 6},
                            new ilce() {Id = 77, Name = "GÖLBAŞI", ilId = 6},
                            new ilce() {Id = 78, Name = "GÜDÜL", ilId = 6},
                            new ilce() {Id = 79, Name = "HAYMANA", ilId = 6},
                            new ilce() {Id = 80, Name = "KAHRAMANKAZAN", ilId = 6},
                            new ilce() {Id = 81, Name = "KALECİK", ilId = 6},
                            new ilce() {Id = 82, Name = "KEÇİÖREN", ilId = 6},
                            new ilce() {Id = 83, Name = "KIZILCAHAMAM", ilId = 6},
                            new ilce() {Id = 84, Name = "MAMAK", ilId = 6},
                            new ilce() {Id = 85, Name = "NALLIHAN", ilId = 6},
                            new ilce() {Id = 86, Name = "POLATLI", ilId = 6},
                            new ilce() {Id = 87, Name = "PURSAKLAR", ilId = 6},
                            new ilce() {Id = 88, Name = "SİNCAN", ilId = 6},
                            new ilce() {Id = 89, Name = "ŞEREFLİKOÇHİSAR", ilId = 6},
                            new ilce() {Id = 90, Name = "YENİMAHALLE", ilId = 6},
                            new ilce() {Id = 91, Name = "AKSEKİ", ilId = 7},
                            new ilce() {Id = 92, Name = "AKSU", ilId = 7},
                            new ilce() {Id = 93, Name = "ALANYA", ilId = 7},
                            new ilce() {Id = 94, Name = "DEMRE", ilId = 7},
                            new ilce() {Id = 95, Name = "DÖŞEMEALTI", ilId = 7},
                            new ilce() {Id = 96, Name = "ELMALI", ilId = 7},
                            new ilce() {Id = 97, Name = "FİNİKE", ilId = 7},
                            new ilce() {Id = 98, Name = "GAZİPAŞA", ilId = 7},
                            new ilce() {Id = 99, Name = "GÜNDOĞMUŞ", ilId = 7},
                            new ilce() {Id = 100, Name = "İBRADI", ilId = 7},
                            new ilce() {Id = 101, Name = "KAŞ", ilId = 7},
                            new ilce() {Id = 102, Name = "KEMER", ilId = 7},
                            new ilce() {Id = 103, Name = "KEPEZ", ilId = 7},
                            new ilce() {Id = 104, Name = "KONYAALTI", ilId = 7},
                            new ilce() {Id = 105, Name = "KORKUTELİ", ilId = 7},
                            new ilce() {Id = 106, Name = "KUMLUCA", ilId = 7},
                            new ilce() {Id = 107, Name = "MANAVGAT", ilId = 7},
                            new ilce() {Id = 108, Name = "MURATPAŞA", ilId = 7},
                            new ilce() {Id = 109, Name = "SERİK", ilId = 7},
                            new ilce() {Id = 110, Name = "ÇILDIR", ilId = 75},
                            new ilce() {Id = 111, Name = "DAMAL", ilId = 75},
                            new ilce() {Id = 112, Name = "GÖLE", ilId = 75},
                            new ilce() {Id = 113, Name = "HANAK", ilId = 75},
                            new ilce() {Id = 114, Name = "MERKEZ", ilId = 75},
                            new ilce() {Id = 115, Name = "POSOF", ilId = 75},
                            new ilce() {Id = 116, Name = "ARDANUÇ", ilId = 8},
                            new ilce() {Id = 117, Name = "ARHAVİ", ilId = 8},
                            new ilce() {Id = 118, Name = "BORÇKA", ilId = 8},
                            new ilce() {Id = 119, Name = "HOPA", ilId = 8},
                            new ilce() {Id = 120, Name = "KEMALPAŞA", ilId = 8},
                            new ilce() {Id = 121, Name = "MERKEZ", ilId = 8},
                            new ilce() {Id = 122, Name = "MURGUL", ilId = 8},
                            new ilce() {Id = 123, Name = "ŞAVŞAT", ilId = 8},
                            new ilce() {Id = 124, Name = "YUSUFELİ", ilId = 8},
                            new ilce() {Id = 125, Name = "BOZDOĞAN", ilId = 9},
                            new ilce() {Id = 126, Name = "BUHARKENT", ilId = 9},
                            new ilce() {Id = 127, Name = "ÇİNE", ilId = 9},
                            new ilce() {Id = 128, Name = "DİDİM", ilId = 9},
                            new ilce() {Id = 129, Name = "EFELER", ilId = 9},
                            new ilce() {Id = 130, Name = "GERMENCİK", ilId = 9},
                            new ilce() {Id = 131, Name = "İNCİRLİOVA", ilId = 9},
                            new ilce() {Id = 132, Name = "KARACASU", ilId = 9},
                            new ilce() {Id = 133, Name = "KARPUZLU", ilId = 9},
                            new ilce() {Id = 134, Name = "KOÇARLI", ilId = 9},
                            new ilce() {Id = 135, Name = "KÖŞK", ilId = 9},
                            new ilce() {Id = 136, Name = "KUŞADASI", ilId = 9},
                            new ilce() {Id = 137, Name = "KUYUCAK", ilId = 9},
                            new ilce() {Id = 138, Name = "NAZİLLİ", ilId = 9},
                            new ilce() {Id = 139, Name = "SÖKE", ilId = 9},
                            new ilce() {Id = 140, Name = "SULTANHİSAR", ilId = 9},
                            new ilce() {Id = 141, Name = "YENİPAZAR", ilId = 9},
                            new ilce() {Id = 142, Name = "ALTIEYLÜL", ilId = 10},
                            new ilce() {Id = 143, Name = "AYVALIK", ilId = 10},
                            new ilce() {Id = 144, Name = "BALYA", ilId = 10},
                            new ilce() {Id = 145, Name = "BANDIRMA", ilId = 10},
                            new ilce() {Id = 146, Name = "BİGADİÇ", ilId = 10},
                            new ilce() {Id = 147, Name = "BURHANİYE", ilId = 10},
                            new ilce() {Id = 148, Name = "DURSUNBEY", ilId = 10},
                            new ilce() {Id = 149, Name = "EDREMİT", ilId = 10},
                            new ilce() {Id = 150, Name = "ERDEK", ilId = 10},
                            new ilce() {Id = 151, Name = "GÖMEÇ", ilId = 10},
                            new ilce() {Id = 152, Name = "GÖNEN", ilId = 10},
                            new ilce() {Id = 153, Name = "HAVRAN", ilId = 10},
                            new ilce() {Id = 154, Name = "İVRİNDİ", ilId = 10},
                            new ilce() {Id = 155, Name = "KARESİ", ilId = 10},
                            new ilce() {Id = 156, Name = "KEPSUT", ilId = 10},
                            new ilce() {Id = 157, Name = "MANYAS", ilId = 10},
                            new ilce() {Id = 158, Name = "MARMARA", ilId = 10},
                            new ilce() {Id = 159, Name = "SAVAŞTEPE", ilId = 10},
                            new ilce() {Id = 160, Name = "SINDIRGI", ilId = 10},
                            new ilce() {Id = 161, Name = "SUSURLUK", ilId = 10},
                            new ilce() {Id = 162, Name = "AMASRA", ilId = 74},
                            new ilce() {Id = 163, Name = "KURUCAŞİLE", ilId = 74},
                            new ilce() {Id = 164, Name = "MERKEZ", ilId = 74},
                            new ilce() {Id = 165, Name = "ULUS", ilId = 74},
                            new ilce() {Id = 166, Name = "BEŞİRİ", ilId = 72},
                            new ilce() {Id = 167, Name = "GERCÜŞ", ilId = 72},
                            new ilce() {Id = 168, Name = "HASANKEYF", ilId = 72},
                            new ilce() {Id = 169, Name = "KOZLUK", ilId = 72},
                            new ilce() {Id = 170, Name = "MERKEZ", ilId = 72},
                            new ilce() {Id = 171, Name = "SASON", ilId = 72},
                            new ilce() {Id = 172, Name = "AYDINTEPE", ilId = 69},
                            new ilce() {Id = 173, Name = "DEMİRÖZÜ", ilId = 69},
                            new ilce() {Id = 174, Name = "MERKEZ", ilId = 69},
                            new ilce() {Id = 175, Name = "BOZÜYÜK", ilId = 11},
                            new ilce() {Id = 176, Name = "GÖLPAZARI", ilId = 11},
                            new ilce() {Id = 177, Name = "İNHİSAR", ilId = 11},
                            new ilce() {Id = 178, Name = "MERKEZ", ilId = 11},
                            new ilce() {Id = 179, Name = "OSMANELİ", ilId = 11},
                            new ilce() {Id = 180, Name = "PAZARYERİ", ilId = 11},
                            new ilce() {Id = 181, Name = "SÖĞÜT", ilId = 11},
                            new ilce() {Id = 182, Name = "YENİPAZAR", ilId = 11},
                            new ilce() {Id = 183, Name = "ADAKLI", ilId = 12},
                            new ilce() {Id = 184, Name = "GENÇ", ilId = 12},
                            new ilce() {Id = 185, Name = "KARLIOVA", ilId = 12},
                            new ilce() {Id = 186, Name = "KİĞI", ilId = 12},
                            new ilce() {Id = 187, Name = "MERKEZ", ilId = 12},
                            new ilce() {Id = 188, Name = "SOLHAN", ilId = 12},
                            new ilce() {Id = 189, Name = "YAYLADERE", ilId = 12},
                            new ilce() {Id = 190, Name = "YEDİSU", ilId = 12},
                            new ilce() {Id = 191, Name = "ADİLCEVAZ", ilId = 13},
                            new ilce() {Id = 192, Name = "AHLAT", ilId = 13},
                            new ilce() {Id = 193, Name = "GÜROYMAK", ilId = 13},
                            new ilce() {Id = 194, Name = "HİZAN", ilId = 13},
                            new ilce() {Id = 195, Name = "MERKEZ", ilId = 13},
                            new ilce() {Id = 196, Name = "MUTKİ", ilId = 13},
                            new ilce() {Id = 197, Name = "TATVAN", ilId = 13},
                            new ilce() {Id = 198, Name = "DÖRTDİVAN", ilId = 14},
                            new ilce() {Id = 199, Name = "GEREDE", ilId = 14},
                            new ilce() {Id = 200, Name = "GÖYNÜK", ilId = 14},
                            new ilce() {Id = 201, Name = "KIBRISCIK", ilId = 14},
                            new ilce() {Id = 202, Name = "MENGEN", ilId = 14},
                            new ilce() {Id = 203, Name = "MERKEZ", ilId = 14},
                            new ilce() {Id = 204, Name = "MUDURNU", ilId = 14},
                            new ilce() {Id = 205, Name = "SEBEN", ilId = 14},
                            new ilce() {Id = 206, Name = "YENİÇAĞA", ilId = 14},
                            new ilce() {Id = 207, Name = "AĞLASUN", ilId = 15},
                            new ilce() {Id = 208, Name = "ALTINYAYLA", ilId = 15},
                            new ilce() {Id = 209, Name = "BUCAK", ilId = 15},
                            new ilce() {Id = 210, Name = "ÇAVDIR", ilId = 15},
                            new ilce() {Id = 211, Name = "ÇELTİKÇİ", ilId = 15},
                            new ilce() {Id = 212, Name = "GÖLHİSAR", ilId = 15},
                            new ilce() {Id = 213, Name = "KARAMANLI", ilId = 15},
                            new ilce() {Id = 214, Name = "KEMER", ilId = 15},
                            new ilce() {Id = 215, Name = "MERKEZ", ilId = 15},
                            new ilce() {Id = 216, Name = "TEFENNİ", ilId = 15},
                            new ilce() {Id = 217, Name = "YEŞİLOVA", ilId = 15},
                            new ilce() {Id = 218, Name = "BÜYÜKORHAN", ilId = 16},
                            new ilce() {Id = 219, Name = "GEMLİK", ilId = 16},
                            new ilce() {Id = 220, Name = "GÜRSU", ilId = 16},
                            new ilce() {Id = 221, Name = "HARMANCIK", ilId = 16},
                            new ilce() {Id = 222, Name = "İNEGÖL", ilId = 16},
                            new ilce() {Id = 223, Name = "İZNİK", ilId = 16},
                            new ilce() {Id = 224, Name = "KARACABEY", ilId = 16},
                            new ilce() {Id = 225, Name = "KELES", ilId = 16},
                            new ilce() {Id = 226, Name = "KESTEL", ilId = 16},
                            new ilce() {Id = 227, Name = "MUDANYA", ilId = 16},
                            new ilce() {Id = 228, Name = "MUSTAFAKEMALPAŞA", ilId = 16},
                            new ilce() {Id = 229, Name = "NİLÜFER", ilId = 16},
                            new ilce() {Id = 230, Name = "ORHANELİ", ilId = 16},
                            new ilce() {Id = 231, Name = "ORHANGAZİ", ilId = 16},
                            new ilce() {Id = 232, Name = "OSMANGAZİ", ilId = 16},
                            new ilce() {Id = 233, Name = "YENİŞEHİR", ilId = 16},
                            new ilce() {Id = 234, Name = "YILDIRIM", ilId = 16},
                            new ilce() {Id = 235, Name = "AYVACIK", ilId = 17},
                            new ilce() {Id = 236, Name = "BAYRAMİÇ", ilId = 17},
                            new ilce() {Id = 237, Name = "BİGA", ilId = 17},
                            new ilce() {Id = 238, Name = "BOZCAADA", ilId = 17},
                            new ilce() {Id = 239, Name = "ÇAN", ilId = 17},
                            new ilce() {Id = 240, Name = "ECEABAT", ilId = 17},
                            new ilce() {Id = 241, Name = "EZİNE", ilId = 17},
                            new ilce() {Id = 242, Name = "GELİBOLU", ilId = 17},
                            new ilce() {Id = 243, Name = "GÖKÇEADA", ilId = 17},
                            new ilce() {Id = 244, Name = "LAPSEKİ", ilId = 17},
                            new ilce() {Id = 245, Name = "MERKEZ", ilId = 17},
                            new ilce() {Id = 246, Name = "YENİCE", ilId = 17},
                            new ilce() {Id = 247, Name = "ATKARACALAR", ilId = 18},
                            new ilce() {Id = 248, Name = "BAYRAMÖREN", ilId = 18},
                            new ilce() {Id = 249, Name = "ÇERKEŞ", ilId = 18},
                            new ilce() {Id = 250, Name = "ELDİVAN", ilId = 18},
                            new ilce() {Id = 251, Name = "ILGAZ", ilId = 18},
                            new ilce() {Id = 252, Name = "KIZILIRMAK", ilId = 18},
                            new ilce() {Id = 253, Name = "KORGUN", ilId = 18},
                            new ilce() {Id = 254, Name = "KURŞUNLU", ilId = 18},
                            new ilce() {Id = 255, Name = "MERKEZ", ilId = 18},
                            new ilce() {Id = 256, Name = "ORTA", ilId = 18},
                            new ilce() {Id = 257, Name = "ŞABANÖZÜ", ilId = 18},
                            new ilce() {Id = 258, Name = "YAPRAKLI", ilId = 18},
                            new ilce() {Id = 259, Name = "ALACA", ilId = 19},
                            new ilce() {Id = 260, Name = "BAYAT", ilId = 19},
                            new ilce() {Id = 261, Name = "BOĞAZKALE", ilId = 19},
                            new ilce() {Id = 262, Name = "DODURGA", ilId = 19},
                            new ilce() {Id = 263, Name = "İSKİLİP", ilId = 19},
                            new ilce() {Id = 264, Name = "KARGI", ilId = 19},
                            new ilce() {Id = 265, Name = "LAÇİN", ilId = 19},
                            new ilce() {Id = 266, Name = "MECİTÖZÜ", ilId = 19},
                            new ilce() {Id = 267, Name = "MERKEZ", ilId = 19},
                            new ilce() {Id = 268, Name = "OĞUZLAR", ilId = 19},
                            new ilce() {Id = 269, Name = "ORTAKÖY", ilId = 19},
                            new ilce() {Id = 270, Name = "OSMANCIK", ilId = 19},
                            new ilce() {Id = 271, Name = "SUNGURLU", ilId = 19},
                            new ilce() {Id = 272, Name = "UĞURLUDAĞ", ilId = 19},
                            new ilce() {Id = 273, Name = "ACIPAYAM", ilId = 20},
                            new ilce() {Id = 274, Name = "BABADAĞ", ilId = 20},
                            new ilce() {Id = 275, Name = "BAKLAN", ilId = 20},
                            new ilce() {Id = 276, Name = "BEKİLLİ", ilId = 20},
                            new ilce() {Id = 277, Name = "BEYAĞAÇ", ilId = 20},
                            new ilce() {Id = 278, Name = "BOZKURT", ilId = 20},
                            new ilce() {Id = 279, Name = "BULDAN", ilId = 20},
                            new ilce() {Id = 280, Name = "ÇAL", ilId = 20},
                            new ilce() {Id = 281, Name = "ÇAMELİ", ilId = 20},
                            new ilce() {Id = 282, Name = "ÇARDAK", ilId = 20},
                            new ilce() {Id = 283, Name = "ÇİVRİL", ilId = 20},
                            new ilce() {Id = 284, Name = "GÜNEY", ilId = 20},
                            new ilce() {Id = 285, Name = "HONAZ", ilId = 20},
                            new ilce() {Id = 286, Name = "KALE", ilId = 20},
                            new ilce() {Id = 287, Name = "MERKEZEFENDİ", ilId = 20},
                            new ilce() {Id = 288, Name = "PAMUKKALE", ilId = 20},
                            new ilce() {Id = 289, Name = "SARAYKÖY", ilId = 20},
                            new ilce() {Id = 290, Name = "SERİNHİSAR", ilId = 20},
                            new ilce() {Id = 291, Name = "TAVAS", ilId = 20},
                            new ilce() {Id = 292, Name = "BAĞLAR", ilId = 21},
                            new ilce() {Id = 293, Name = "BİSMİL", ilId = 21},
                            new ilce() {Id = 294, Name = "ÇERMİK", ilId = 21},
                            new ilce() {Id = 295, Name = "ÇINAR", ilId = 21},
                            new ilce() {Id = 296, Name = "ÇÜNGÜŞ", ilId = 21},
                            new ilce() {Id = 297, Name = "DİCLE", ilId = 21},
                            new ilce() {Id = 298, Name = "EĞİL", ilId = 21},
                            new ilce() {Id = 299, Name = "ERGANİ", ilId = 21},
                            new ilce() {Id = 300, Name = "HANİ", ilId = 21},
                            new ilce() {Id = 301, Name = "HAZRO", ilId = 21},
                            new ilce() {Id = 302, Name = "KAYAPINAR", ilId = 21},
                            new ilce() {Id = 303, Name = "KOCAKÖY", ilId = 21},
                            new ilce() {Id = 304, Name = "KULP", ilId = 21},
                            new ilce() {Id = 305, Name = "LİCE", ilId = 21},
                            new ilce() {Id = 306, Name = "SİLVAN", ilId = 21},
                            new ilce() {Id = 307, Name = "SUR", ilId = 21},
                            new ilce() {Id = 308, Name = "YENİŞEHİR", ilId = 21},
                            new ilce() {Id = 309, Name = "AKÇAKOCA", ilId = 81},
                            new ilce() {Id = 310, Name = "CUMAYERİ", ilId = 81},
                            new ilce() {Id = 311, Name = "ÇİLİMLİ", ilId = 81},
                            new ilce() {Id = 312, Name = "GÖLYAKA", ilId = 81},
                            new ilce() {Id = 313, Name = "GÜMÜŞOVA", ilId = 81},
                            new ilce() {Id = 314, Name = "KAYNAŞLI", ilId = 81},
                            new ilce() {Id = 315, Name = "MERKEZ", ilId = 81},
                            new ilce() {Id = 316, Name = "YIĞILCA", ilId = 81},
                            new ilce() {Id = 317, Name = "ENEZ", ilId = 22},
                            new ilce() {Id = 318, Name = "HAVSA", ilId = 22},
                            new ilce() {Id = 319, Name = "İPSALA", ilId = 22},
                            new ilce() {Id = 320, Name = "KEŞAN", ilId = 22},
                            new ilce() {Id = 321, Name = "LALAPAŞA", ilId = 22},
                            new ilce() {Id = 322, Name = "MERİÇ", ilId = 22},
                            new ilce() {Id = 323, Name = "MERKEZ", ilId = 22},
                            new ilce() {Id = 324, Name = "SÜLOĞLU", ilId = 22},
                            new ilce() {Id = 325, Name = "UZUNKÖPRÜ", ilId = 22},
                            new ilce() {Id = 326, Name = "AĞIN", ilId = 23},
                            new ilce() {Id = 327, Name = "ALACAKAYA", ilId = 23},
                            new ilce() {Id = 328, Name = "ARICAK", ilId = 23},
                            new ilce() {Id = 329, Name = "BASKİL", ilId = 23},
                            new ilce() {Id = 330, Name = "KARAKOÇAN", ilId = 23},
                            new ilce() {Id = 331, Name = "KEBAN", ilId = 23},
                            new ilce() {Id = 332, Name = "KOVANCILAR", ilId = 23},
                            new ilce() {Id = 333, Name = "MADEN", ilId = 23},
                            new ilce() {Id = 334, Name = "MERKEZ", ilId = 23},
                            new ilce() {Id = 335, Name = "PALU", ilId = 23},
                            new ilce() {Id = 336, Name = "SİVRİCE", ilId = 23},
                            new ilce() {Id = 337, Name = "ÇAYIRLI", ilId = 24},
                            new ilce() {Id = 338, Name = "İLİÇ", ilId = 24},
                            new ilce() {Id = 339, Name = "KEMAH", ilId = 24},
                            new ilce() {Id = 340, Name = "KEMALİYE", ilId = 24},
                            new ilce() {Id = 341, Name = "MERKEZ", ilId = 24},
                            new ilce() {Id = 342, Name = "OTLUKBELİ", ilId = 24},
                            new ilce() {Id = 343, Name = "REFAHİYE", ilId = 24},
                            new ilce() {Id = 344, Name = "TERCAN", ilId = 24},
                            new ilce() {Id = 345, Name = "ÜZÜMLÜ", ilId = 24},
                            new ilce() {Id = 346, Name = "AŞKALE", ilId = 25},
                            new ilce() {Id = 347, Name = "AZİZİYE", ilId = 25},
                            new ilce() {Id = 348, Name = "ÇAT", ilId = 25},
                            new ilce() {Id = 349, Name = "HINIS", ilId = 25},
                            new ilce() {Id = 350, Name = "HORASAN", ilId = 25},
                            new ilce() {Id = 351, Name = "İSPİR", ilId = 25},
                            new ilce() {Id = 352, Name = "KARAÇOBAN", ilId = 25},
                            new ilce() {Id = 353, Name = "KARAYAZI", ilId = 25},
                            new ilce() {Id = 354, Name = "KÖPRÜKÖY", ilId = 25},
                            new ilce() {Id = 355, Name = "NARMAN", ilId = 25},
                            new ilce() {Id = 356, Name = "OLTU", ilId = 25},
                            new ilce() {Id = 357, Name = "OLUR", ilId = 25},
                            new ilce() {Id = 358, Name = "PALANDÖKEN", ilId = 25},
                            new ilce() {Id = 359, Name = "PASİNLER", ilId = 25},
                            new ilce() {Id = 360, Name = "PAZARYOLU", ilId = 25},
                            new ilce() {Id = 361, Name = "ŞENKAYA", ilId = 25},
                            new ilce() {Id = 362, Name = "TEKMAN", ilId = 25},
                            new ilce() {Id = 363, Name = "TORTUM", ilId = 25},
                            new ilce() {Id = 364, Name = "UZUNDERE", ilId = 25},
                            new ilce() {Id = 365, Name = "YAKUTİYE", ilId = 25},
                            new ilce() {Id = 366, Name = "ALPU", ilId = 26},
                            new ilce() {Id = 367, Name = "BEYLİKOVA", ilId = 26},
                            new ilce() {Id = 368, Name = "ÇİFTELER", ilId = 26},
                            new ilce() {Id = 369, Name = "GÜNYÜZÜ", ilId = 26},
                            new ilce() {Id = 370, Name = "HAN", ilId = 26},
                            new ilce() {Id = 371, Name = "İNÖNÜ", ilId = 26},
                            new ilce() {Id = 372, Name = "MAHMUDİYE", ilId = 26},
                            new ilce() {Id = 373, Name = "MİHALGAZİ", ilId = 26},
                            new ilce() {Id = 374, Name = "MİHALIÇÇIK", ilId = 26},
                            new ilce() {Id = 375, Name = "ODUNPAZARI", ilId = 26},
                            new ilce() {Id = 376, Name = "SARICAKAYA", ilId = 26},
                            new ilce() {Id = 377, Name = "SEYİTGAZİ", ilId = 26},
                            new ilce() {Id = 378, Name = "SİVRİHİSAR", ilId = 26},
                            new ilce() {Id = 379, Name = "TEPEBAŞI", ilId = 26},
                            new ilce() {Id = 380, Name = "ARABAN", ilId = 27},
                            new ilce() {Id = 381, Name = "İSLAHİYE", ilId = 27},
                            new ilce() {Id = 382, Name = "KARKAMIŞ", ilId = 27},
                            new ilce() {Id = 383, Name = "NİZİP", ilId = 27},
                            new ilce() {Id = 384, Name = "NURDAĞI", ilId = 27},
                            new ilce() {Id = 385, Name = "OĞUZELİ", ilId = 27},
                            new ilce() {Id = 386, Name = "ŞAHİNBEY", ilId = 27},
                            new ilce() {Id = 387, Name = "ŞEHİTKAMİL", ilId = 27},
                            new ilce() {Id = 388, Name = "YAVUZELİ", ilId = 27},
                            new ilce() {Id = 389, Name = "ALUCRA", ilId = 28},
                            new ilce() {Id = 390, Name = "BULANCAK", ilId = 28},
                            new ilce() {Id = 391, Name = "ÇAMOLUK", ilId = 28},
                            new ilce() {Id = 392, Name = "ÇANAKÇI", ilId = 28},
                            new ilce() {Id = 393, Name = "DERELİ", ilId = 28},
                            new ilce() {Id = 394, Name = "DOĞANKENT", ilId = 28},
                            new ilce() {Id = 395, Name = "ESPİYE", ilId = 28},
                            new ilce() {Id = 396, Name = "EYNESİL", ilId = 28},
                            new ilce() {Id = 397, Name = "GÖRELE", ilId = 28},
                            new ilce() {Id = 398, Name = "GÜCE", ilId = 28},
                            new ilce() {Id = 399, Name = "KEŞAP", ilId = 28},
                            new ilce() {Id = 400, Name = "MERKEZ", ilId = 28},
                            new ilce() {Id = 401, Name = "PİRAZİZ", ilId = 28},
                            new ilce() {Id = 402, Name = "ŞEBİNKARAHİSAR", ilId = 28},
                            new ilce() {Id = 403, Name = "TİREBOLU", ilId = 28},
                            new ilce() {Id = 404, Name = "YAĞLIDERE", ilId = 28},
                            new ilce() {Id = 405, Name = "KELKİT", ilId = 29},
                            new ilce() {Id = 406, Name = "KÖSE", ilId = 29},
                            new ilce() {Id = 407, Name = "KÜRTÜN", ilId = 29},
                            new ilce() {Id = 408, Name = "MERKEZ", ilId = 29},
                            new ilce() {Id = 409, Name = "ŞİRAN", ilId = 29},
                            new ilce() {Id = 410, Name = "TORUL", ilId = 29},
                            new ilce() {Id = 411, Name = "ÇUKURCA", ilId = 30},
                            new ilce() {Id = 412, Name = "DERECİK", ilId = 30},
                            new ilce() {Id = 413, Name = "MERKEZ", ilId = 30},
                            new ilce() {Id = 414, Name = "ŞEMDİNLİ", ilId = 30},
                            new ilce() {Id = 415, Name = "YÜKSEKOVA", ilId = 30},
                            new ilce() {Id = 416, Name = "ALTINÖZÜ", ilId = 31},
                            new ilce() {Id = 417, Name = "ANTAKYA", ilId = 31},
                            new ilce() {Id = 418, Name = "ARSUZ", ilId = 31},
                            new ilce() {Id = 419, Name = "BELEN", ilId = 31},
                            new ilce() {Id = 420, Name = "DEFNE", ilId = 31},
                            new ilce() {Id = 421, Name = "DÖRTYOL", ilId = 31},
                            new ilce() {Id = 422, Name = "ERZİN", ilId = 31},
                            new ilce() {Id = 423, Name = "HASSA", ilId = 31},
                            new ilce() {Id = 424, Name = "İSKENDERUN", ilId = 31},
                            new ilce() {Id = 425, Name = "KIRIKHAN", ilId = 31},
                            new ilce() {Id = 426, Name = "KUMLU", ilId = 31},
                            new ilce() {Id = 427, Name = "PAYAS", ilId = 31},
                            new ilce() {Id = 428, Name = "REYHANLI", ilId = 31},
                            new ilce() {Id = 429, Name = "SAMANDAĞ", ilId = 31},
                            new ilce() {Id = 430, Name = "YAYLADAĞI", ilId = 31},
                            new ilce() {Id = 431, Name = "ARALIK", ilId = 76},
                            new ilce() {Id = 432, Name = "KARAKOYUNLU", ilId = 76},
                            new ilce() {Id = 433, Name = "MERKEZ", ilId = 76},
                            new ilce() {Id = 434, Name = "TUZLUCA", ilId = 76},
                            new ilce() {Id = 435, Name = "AKSU", ilId = 32},
                            new ilce() {Id = 436, Name = "ATABEY", ilId = 32},
                            new ilce() {Id = 437, Name = "EĞİRDİR", ilId = 32},
                            new ilce() {Id = 438, Name = "GELENDOST", ilId = 32},
                            new ilce() {Id = 439, Name = "GÖNEN", ilId = 32},
                            new ilce() {Id = 440, Name = "KEÇİBORLU", ilId = 32},
                            new ilce() {Id = 441, Name = "MERKEZ", ilId = 32},
                            new ilce() {Id = 442, Name = "SENİRKENT", ilId = 32},
                            new ilce() {Id = 443, Name = "SÜTÇÜLER", ilId = 32},
                            new ilce() {Id = 444, Name = "ŞARKİKARAAĞAÇ", ilId = 32},
                            new ilce() {Id = 445, Name = "ULUBORLU", ilId = 32},
                            new ilce() {Id = 446, Name = "YALVAÇ", ilId = 32},
                            new ilce() {Id = 447, Name = "YENİŞARBADEMLİ", ilId = 32},
                            new ilce() {Id = 448, Name = "ADALAR", ilId = 34},
                            new ilce() {Id = 449, Name = "ARNAVUTKÖY", ilId = 34},
                            new ilce() {Id = 450, Name = "ATAŞEHİR", ilId = 34},
                            new ilce() {Id = 451, Name = "AVCILAR", ilId = 34},
                            new ilce() {Id = 452, Name = "BAĞCILAR", ilId = 34},
                            new ilce() {Id = 453, Name = "BAHÇELİEVLER", ilId = 34},
                            new ilce() {Id = 454, Name = "BAKIRKÖY", ilId = 34},
                            new ilce() {Id = 455, Name = "BAŞAKŞEHİR", ilId = 34},
                            new ilce() {Id = 456, Name = "BAYRAMPAŞA", ilId = 34},
                            new ilce() {Id = 457, Name = "BEŞİKTAŞ", ilId = 34},
                            new ilce() {Id = 458, Name = "BEYKOZ", ilId = 34},
                            new ilce() {Id = 459, Name = "BEYLİKDÜZÜ", ilId = 34},
                            new ilce() {Id = 460, Name = "BEYOĞLU", ilId = 34},
                            new ilce() {Id = 461, Name = "BÜYÜKÇEKMECE", ilId = 34},
                            new ilce() {Id = 462, Name = "ÇATALCA", ilId = 34},
                            new ilce() {Id = 463, Name = "ÇEKMEKÖY", ilId = 34},
                            new ilce() {Id = 464, Name = "ESENLER", ilId = 34},
                            new ilce() {Id = 465, Name = "ESENYURT", ilId = 34},
                            new ilce() {Id = 466, Name = "EYÜPSULTAN", ilId = 34},
                            new ilce() {Id = 467, Name = "FATİH", ilId = 34},
                            new ilce() {Id = 468, Name = "GAZİOSMANPAŞA", ilId = 34},
                            new ilce() {Id = 469, Name = "GÜNGÖREN", ilId = 34},
                            new ilce() {Id = 470, Name = "KADIKÖY", ilId = 34},
                            new ilce() {Id = 471, Name = "KAĞITHANE", ilId = 34},
                            new ilce() {Id = 472, Name = "KARTAL", ilId = 34},
                            new ilce() {Id = 473, Name = "KÜÇÜKÇEKMECE", ilId = 34},
                            new ilce() {Id = 474, Name = "MALTEPE", ilId = 34},
                            new ilce() {Id = 475, Name = "PENDİK", ilId = 34},
                            new ilce() {Id = 476, Name = "SANCAKTEPE", ilId = 34},
                            new ilce() {Id = 477, Name = "SARIYER", ilId = 34},
                            new ilce() {Id = 478, Name = "SİLİVRİ", ilId = 34},
                            new ilce() {Id = 479, Name = "SULTANBEYLİ", ilId = 34},
                            new ilce() {Id = 480, Name = "SULTANGAZİ", ilId = 34},
                            new ilce() {Id = 481, Name = "ŞİLE", ilId = 34},
                            new ilce() {Id = 482, Name = "ŞİŞLİ", ilId = 34},
                            new ilce() {Id = 483, Name = "TUZLA", ilId = 34},
                            new ilce() {Id = 484, Name = "ÜMRANİYE", ilId = 34},
                            new ilce() {Id = 485, Name = "ÜSKÜDAR", ilId = 34},
                            new ilce() {Id = 486, Name = "ZEYTİNBURNU", ilId = 34},
                            new ilce() {Id = 487, Name = "ALİAĞA", ilId = 35},
                            new ilce() {Id = 488, Name = "BALÇOVA", ilId = 35},
                            new ilce() {Id = 489, Name = "BAYINDIR", ilId = 35},
                            new ilce() {Id = 490, Name = "BAYRAKLI", ilId = 35},
                            new ilce() {Id = 491, Name = "BERGAMA", ilId = 35},
                            new ilce() {Id = 492, Name = "BEYDAĞ", ilId = 35},
                            new ilce() {Id = 493, Name = "BORNOVA", ilId = 35},
                            new ilce() {Id = 494, Name = "BUCA", ilId = 35},
                            new ilce() {Id = 495, Name = "ÇEŞME", ilId = 35},
                            new ilce() {Id = 496, Name = "ÇİĞLİ", ilId = 35},
                            new ilce() {Id = 497, Name = "DİKİLİ", ilId = 35},
                            new ilce() {Id = 498, Name = "FOÇA", ilId = 35},
                            new ilce() {Id = 499, Name = "GAZİEMİR", ilId = 35},
                            new ilce() {Id = 500, Name = "GÜZELBAHÇE", ilId = 35},
                            new ilce() {Id = 501, Name = "KARABAĞLAR", ilId = 35},
                            new ilce() {Id = 502, Name = "KARABURUN", ilId = 35},
                            new ilce() {Id = 503, Name = "KARŞIYAKA", ilId = 35},
                            new ilce() {Id = 504, Name = "KEMALPAŞA", ilId = 35},
                            new ilce() {Id = 505, Name = "KINIK", ilId = 35},
                            new ilce() {Id = 506, Name = "KİRAZ", ilId = 35},
                            new ilce() {Id = 507, Name = "KONAK", ilId = 35},
                            new ilce() {Id = 508, Name = "MENDERES", ilId = 35},
                            new ilce() {Id = 509, Name = "MENEMEN", ilId = 35},
                            new ilce() {Id = 510, Name = "NARLIDERE", ilId = 35},
                            new ilce() {Id = 511, Name = "ÖDEMİŞ", ilId = 35},
                            new ilce() {Id = 512, Name = "SEFERİHİSAR", ilId = 35},
                            new ilce() {Id = 513, Name = "SELÇUK", ilId = 35},
                            new ilce() {Id = 514, Name = "TİRE", ilId = 35},
                            new ilce() {Id = 515, Name = "TORBALI", ilId = 35},
                            new ilce() {Id = 516, Name = "URLA", ilId = 35},
                            new ilce() {Id = 517, Name = "AFŞİN", ilId = 46},
                            new ilce() {Id = 518, Name = "ANDIRIN", ilId = 46},
                            new ilce() {Id = 519, Name = "ÇAĞLAYANCERİT", ilId = 46},
                            new ilce() {Id = 520, Name = "DULKADİROĞLU", ilId = 46},
                            new ilce() {Id = 521, Name = "EKİNÖZÜ", ilId = 46},
                            new ilce() {Id = 522, Name = "ELBİSTAN", ilId = 46},
                            new ilce() {Id = 523, Name = "GÖKSUN", ilId = 46},
                            new ilce() {Id = 524, Name = "NURHAK", ilId = 46},
                            new ilce() {Id = 525, Name = "ONİKİŞUBAT", ilId = 46},
                            new ilce() {Id = 526, Name = "PAZARCIK", ilId = 46},
                            new ilce() {Id = 527, Name = "TÜRKOĞLU", ilId = 46},
                            new ilce() {Id = 528, Name = "EFLANİ", ilId = 78},
                            new ilce() {Id = 529, Name = "ESKİPAZAR", ilId = 78},
                            new ilce() {Id = 530, Name = "MERKEZ", ilId = 78},
                            new ilce() {Id = 531, Name = "OVACIK", ilId = 78},
                            new ilce() {Id = 532, Name = "SAFRANBOLU", ilId = 78},
                            new ilce() {Id = 533, Name = "YENİCE", ilId = 78},
                            new ilce() {Id = 534, Name = "AYRANCI", ilId = 70},
                            new ilce() {Id = 535, Name = "BAŞYAYLA", ilId = 70},
                            new ilce() {Id = 536, Name = "ERMENEK", ilId = 70},
                            new ilce() {Id = 537, Name = "KAZIMKARABEKİR", ilId = 70},
                            new ilce() {Id = 538, Name = "MERKEZ", ilId = 70},
                            new ilce() {Id = 539, Name = "SARIVELİLER", ilId = 70},
                            new ilce() {Id = 540, Name = "AKYAKA", ilId = 36},
                            new ilce() {Id = 541, Name = "ARPAÇAY", ilId = 36},
                            new ilce() {Id = 542, Name = "DİGOR", ilId = 36},
                            new ilce() {Id = 543, Name = "KAĞIZMAN", ilId = 36},
                            new ilce() {Id = 544, Name = "MERKEZ", ilId = 36},
                            new ilce() {Id = 545, Name = "SARIKAMIŞ", ilId = 36},
                            new ilce() {Id = 546, Name = "SELİM", ilId = 36},
                            new ilce() {Id = 547, Name = "SUSUZ", ilId = 36},
                            new ilce() {Id = 548, Name = "ABANA", ilId = 37},
                            new ilce() {Id = 549, Name = "AĞLI", ilId = 37},
                            new ilce() {Id = 550, Name = "ARAÇ", ilId = 37},
                            new ilce() {Id = 551, Name = "AZDAVAY", ilId = 37},
                            new ilce() {Id = 552, Name = "BOZKURT", ilId = 37},
                            new ilce() {Id = 553, Name = "CİDE", ilId = 37},
                            new ilce() {Id = 554, Name = "ÇATALZEYTİN", ilId = 37},
                            new ilce() {Id = 555, Name = "DADAY", ilId = 37},
                            new ilce() {Id = 556, Name = "DEVREKANİ", ilId = 37},
                            new ilce() {Id = 557, Name = "DOĞANYURT", ilId = 37},
                            new ilce() {Id = 558, Name = "HANÖNÜ", ilId = 37},
                            new ilce() {Id = 559, Name = "İHSANGAZİ", ilId = 37},
                            new ilce() {Id = 560, Name = "İNEBOLU", ilId = 37},
                            new ilce() {Id = 561, Name = "KÜRE", ilId = 37},
                            new ilce() {Id = 562, Name = "MERKEZ", ilId = 37},
                            new ilce() {Id = 563, Name = "PINARBAŞI", ilId = 37},
                            new ilce() {Id = 564, Name = "SEYDİLER", ilId = 37},
                            new ilce() {Id = 565, Name = "ŞENPAZAR", ilId = 37},
                            new ilce() {Id = 566, Name = "TAŞKÖPRÜ", ilId = 37},
                            new ilce() {Id = 567, Name = "TOSYA", ilId = 37},
                            new ilce() {Id = 568, Name = "AFŞİN", ilId = 46},
                            new ilce() {Id = 569, Name = "ANDIRIN", ilId = 46},
                            new ilce() {Id = 570, Name = "ÇAĞLAYANCERİT", ilId = 46},
                            new ilce() {Id = 571, Name = "DULKADİROĞLU", ilId = 46},
                            new ilce() {Id = 572, Name = "EKİNÖZÜ", ilId = 46},
                            new ilce() {Id = 573, Name = "ELBİSTAN", ilId = 46},
                            new ilce() {Id = 574, Name = "GÖKSUN", ilId = 46},
                            new ilce() {Id = 575, Name = "NURHAK", ilId = 46},
                            new ilce() {Id = 576, Name = "ONİKİŞUBAT", ilId = 46},
                            new ilce() {Id = 577, Name = "PAZARCIK", ilId = 46},
                            new ilce() {Id = 578, Name = "TÜRKOĞLU", ilId = 46},
                            new ilce() {Id = 579, Name = "BAHŞILI", ilId = 71},
                            new ilce() {Id = 580, Name = "BALIŞEYH", ilId = 71},
                            new ilce() {Id = 581, Name = "ÇELEBİ", ilId = 71},
                            new ilce() {Id = 582, Name = "DELİCE", ilId = 71},
                            new ilce() {Id = 583, Name = "KARAKEÇİLİ", ilId = 71},
                            new ilce() {Id = 584, Name = "KESKİN", ilId = 71},
                            new ilce() {Id = 585, Name = "MERKEZ", ilId = 71},
                            new ilce() {Id = 586, Name = "SULAKYURT", ilId = 71},
                            new ilce() {Id = 587, Name = "YAHŞİHAN", ilId = 71},
                            new ilce() {Id = 588, Name = "BABAESKİ", ilId = 39},
                            new ilce() {Id = 589, Name = "DEMİRKÖY", ilId = 39},
                            new ilce() {Id = 590, Name = "KOFÇAZ", ilId = 39},
                            new ilce() {Id = 591, Name = "LÜLEBURGAZ", ilId = 39},
                            new ilce() {Id = 592, Name = "MERKEZ", ilId = 39},
                            new ilce() {Id = 593, Name = "PEHLİVANKÖY", ilId = 39},
                            new ilce() {Id = 594, Name = "PINARHİSAR", ilId = 39},
                            new ilce() {Id = 595, Name = "VİZE", ilId = 39},
                            new ilce() {Id = 596, Name = "AKÇAKENT", ilId = 40},
                            new ilce() {Id = 597, Name = "AKPINAR", ilId = 40},
                            new ilce() {Id = 598, Name = "BOZTEPE", ilId = 40},
                            new ilce() {Id = 599, Name = "ÇİÇEKDAĞI", ilId = 40},
                            new ilce() {Id = 600, Name = "KAMAN", ilId = 40},
                            new ilce() {Id = 601, Name = "MERKEZ", ilId = 40},
                            new ilce() {Id = 602, Name = "MUCUR", ilId = 40},
                            new ilce() {Id = 603, Name = "ELBEYLİ", ilId = 79},
                            new ilce() {Id = 604, Name = "MERKEZ", ilId = 79},
                            new ilce() {Id = 605, Name = "MUSABEYLİ", ilId = 79},
                            new ilce() {Id = 606, Name = "POLATELİ", ilId = 79},
                            new ilce() {Id = 607, Name = "BAŞİSKELE", ilId = 41},
                            new ilce() {Id = 608, Name = "ÇAYIROVA", ilId = 41},
                            new ilce() {Id = 609, Name = "DARICA", ilId = 41},
                            new ilce() {Id = 610, Name = "DERİNCE", ilId = 41},
                            new ilce() {Id = 611, Name = "DİLOVASI", ilId = 41},
                            new ilce() {Id = 612, Name = "GEBZE", ilId = 41},
                            new ilce() {Id = 613, Name = "GÖLCÜK", ilId = 41},
                            new ilce() {Id = 614, Name = "İZMİT", ilId = 41},
                            new ilce() {Id = 615, Name = "KANDIRA", ilId = 41},
                            new ilce() {Id = 616, Name = "KARAMÜRSEL", ilId = 41},
                            new ilce() {Id = 617, Name = "KARTEPE", ilId = 41},
                            new ilce() {Id = 618, Name = "KÖRFEZ", ilId = 41},
                            new ilce() {Id = 619, Name = "AHIRLI", ilId = 42},
                            new ilce() {Id = 620, Name = "AKÖREN", ilId = 42},
                            new ilce() {Id = 621, Name = "AKŞEHİR", ilId = 42},
                            new ilce() {Id = 622, Name = "ALTINEKİN", ilId = 42},
                            new ilce() {Id = 623, Name = "BEYŞEHİR", ilId = 42},
                            new ilce() {Id = 624, Name = "BOZKIR", ilId = 42},
                            new ilce() {Id = 625, Name = "CİHANBEYLİ", ilId = 42},
                            new ilce() {Id = 626, Name = "ÇELTİK", ilId = 42},
                            new ilce() {Id = 627, Name = "ÇUMRA", ilId = 42},
                            new ilce() {Id = 628, Name = "DERBENT", ilId = 42},
                            new ilce() {Id = 629, Name = "DEREBUCAK", ilId = 42},
                            new ilce() {Id = 630, Name = "DOĞANHİSAR", ilId = 42},
                            new ilce() {Id = 631, Name = "EMİRGAZİ", ilId = 42},
                            new ilce() {Id = 632, Name = "EREĞLİ", ilId = 42},
                            new ilce() {Id = 633, Name = "GÜNEYSINIR", ilId = 42},
                            new ilce() {Id = 634, Name = "HADİM", ilId = 42},
                            new ilce() {Id = 635, Name = "HALKAPINAR", ilId = 42},
                            new ilce() {Id = 636, Name = "HÜYÜK", ilId = 42},
                            new ilce() {Id = 637, Name = "ILGIN", ilId = 42},
                            new ilce() {Id = 638, Name = "KADINHANI", ilId = 42},
                            new ilce() {Id = 639, Name = "KARAPINAR", ilId = 42},
                            new ilce() {Id = 640, Name = "KARATAY", ilId = 42},
                            new ilce() {Id = 641, Name = "KULU", ilId = 42},
                            new ilce() {Id = 642, Name = "MERAM", ilId = 42},
                            new ilce() {Id = 643, Name = "SARAYÖNÜ", ilId = 42},
                            new ilce() {Id = 644, Name = "SELÇUKLU", ilId = 42},
                            new ilce() {Id = 645, Name = "SEYDİŞEHİR", ilId = 42},
                            new ilce() {Id = 646, Name = "TAŞKENT", ilId = 42},
                            new ilce() {Id = 647, Name = "TUZLUKÇU", ilId = 42},
                            new ilce() {Id = 648, Name = "YALIHÜYÜK", ilId = 42},
                            new ilce() {Id = 649, Name = "YUNAK", ilId = 42},
                            new ilce() {Id = 650, Name = "ALTINTAŞ", ilId = 43},
                            new ilce() {Id = 651, Name = "ASLANAPA", ilId = 43},
                            new ilce() {Id = 652, Name = "ÇAVDARHİSAR", ilId = 43},
                            new ilce() {Id = 653, Name = "DOMANİÇ", ilId = 43},
                            new ilce() {Id = 654, Name = "DUMLUPINAR", ilId = 43},
                            new ilce() {Id = 655, Name = "EMET", ilId = 43},
                            new ilce() {Id = 656, Name = "GEDİZ", ilId = 43},
                            new ilce() {Id = 657, Name = "HİSARCIK", ilId = 43},
                            new ilce() {Id = 658, Name = "MERKEZ", ilId = 43},
                            new ilce() {Id = 659, Name = "PAZARLAR", ilId = 43},
                            new ilce() {Id = 660, Name = "SİMAV", ilId = 43},
                            new ilce() {Id = 661, Name = "ŞAPHANE", ilId = 43},
                            new ilce() {Id = 662, Name = "TAVŞANLI", ilId = 43},
                            new ilce() {Id = 663, Name = "AKÇADAĞ", ilId = 44},
                            new ilce() {Id = 664, Name = "ARAPGİR", ilId = 44},
                            new ilce() {Id = 665, Name = "ARGUVAN", ilId = 44},
                            new ilce() {Id = 666, Name = "BATTALGAZİ", ilId = 44},
                            new ilce() {Id = 667, Name = "DARENDE", ilId = 44},
                            new ilce() {Id = 668, Name = "DOĞANŞEHİR", ilId = 44},
                            new ilce() {Id = 669, Name = "DOĞANYOL", ilId = 44},
                            new ilce() {Id = 670, Name = "HEKİMHAN", ilId = 44},
                            new ilce() {Id = 671, Name = "KALE", ilId = 44},
                            new ilce() {Id = 672, Name = "KULUNCAK", ilId = 44},
                            new ilce() {Id = 673, Name = "PÜTÜRGE", ilId = 44},
                            new ilce() {Id = 674, Name = "YAZIHAN", ilId = 44},
                            new ilce() {Id = 675, Name = "YEŞİLYURT", ilId = 44},
                            new ilce() {Id = 676, Name = "AHMETLİ", ilId = 45},
                            new ilce() {Id = 677, Name = "AKHİSAR", ilId = 45},
                            new ilce() {Id = 678, Name = "ALAŞEHİR", ilId = 45},
                            new ilce() {Id = 679, Name = "DEMİRCİ", ilId = 45},
                            new ilce() {Id = 680, Name = "GÖLMARMARA", ilId = 45},
                            new ilce() {Id = 681, Name = "GÖRDES", ilId = 45},
                            new ilce() {Id = 682, Name = "KIRKAĞAÇ", ilId = 45},
                            new ilce() {Id = 683, Name = "KÖPRÜBAŞI", ilId = 45},
                            new ilce() {Id = 684, Name = "KULA", ilId = 45},
                            new ilce() {Id = 685, Name = "SALİHLİ", ilId = 45},
                            new ilce() {Id = 686, Name = "SARIGÖL", ilId = 45},
                            new ilce() {Id = 687, Name = "SARUHANLI", ilId = 45},
                            new ilce() {Id = 688, Name = "SELENDİ", ilId = 45},
                            new ilce() {Id = 689, Name = "SOMA", ilId = 45},
                            new ilce() {Id = 690, Name = "ŞEHZADELER", ilId = 45},
                            new ilce() {Id = 691, Name = "TURGUTLU", ilId = 45},
                            new ilce() {Id = 692, Name = "YUNUSEMRE", ilId = 45},
                            new ilce() {Id = 693, Name = "ARTUKLU", ilId = 47},
                            new ilce() {Id = 694, Name = "DARGEÇİT", ilId = 47},
                            new ilce() {Id = 695, Name = "DERİK", ilId = 47},
                            new ilce() {Id = 696, Name = "KIZILTEPE", ilId = 47},
                            new ilce() {Id = 697, Name = "MAZIDAĞI", ilId = 47},
                            new ilce() {Id = 698, Name = "MİDYAT", ilId = 47},
                            new ilce() {Id = 699, Name = "NUSAYBİN", ilId = 47},
                            new ilce() {Id = 700, Name = "ÖMERLİ", ilId = 47},
                            new ilce() {Id = 701, Name = "SAVUR", ilId = 47},
                            new ilce() {Id = 702, Name = "YEŞİLLİ", ilId = 47},
                            new ilce() {Id = 703, Name = "AKDENİZ", ilId = 33},
                            new ilce() {Id = 704, Name = "ANAMUR", ilId = 33},
                            new ilce() {Id = 705, Name = "AYDINCIK", ilId = 33},
                            new ilce() {Id = 706, Name = "BOZYAZI", ilId = 33},
                            new ilce() {Id = 707, Name = "ÇAMLIYAYLA", ilId = 33},
                            new ilce() {Id = 708, Name = "ERDEMLİ", ilId = 33},
                            new ilce() {Id = 709, Name = "GÜLNAR", ilId = 33},
                            new ilce() {Id = 710, Name = "MEZİTLİ", ilId = 33},
                            new ilce() {Id = 711, Name = "MUT", ilId = 33},
                            new ilce() {Id = 712, Name = "SİLİFKE", ilId = 33},
                            new ilce() {Id = 713, Name = "TARSUS", ilId = 33},
                            new ilce() {Id = 714, Name = "TOROSLAR", ilId = 33},
                            new ilce() {Id = 715, Name = "YENİŞEHİR", ilId = 33},
                            new ilce() {Id = 716, Name = "BODRUM", ilId = 48},
                            new ilce() {Id = 717, Name = "DALAMAN", ilId = 48},
                            new ilce() {Id = 718, Name = "DATÇA", ilId = 48},
                            new ilce() {Id = 719, Name = "FETHİYE", ilId = 48},
                            new ilce() {Id = 720, Name = "KAVAKLIDERE", ilId = 48},
                            new ilce() {Id = 721, Name = "KÖYCEĞİZ", ilId = 48},
                            new ilce() {Id = 722, Name = "MARMARİS", ilId = 48},
                            new ilce() {Id = 723, Name = "MENTEŞE", ilId = 48},
                            new ilce() {Id = 724, Name = "MİLAS", ilId = 48},
                            new ilce() {Id = 725, Name = "ORTACA", ilId = 48},
                            new ilce() {Id = 726, Name = "SEYDİKEMER", ilId = 48},
                            new ilce() {Id = 727, Name = "ULA", ilId = 48},
                            new ilce() {Id = 728, Name = "YATAĞAN", ilId = 48},
                            new ilce() {Id = 729, Name = "BULANIK", ilId = 49},
                            new ilce() {Id = 730, Name = "HASKÖY", ilId = 49},
                            new ilce() {Id = 731, Name = "KORKUT", ilId = 49},
                            new ilce() {Id = 732, Name = "MALAZGİRT", ilId = 49},
                            new ilce() {Id = 733, Name = "MERKEZ", ilId = 49},
                            new ilce() {Id = 734, Name = "VARTO", ilId = 49},
                            new ilce() {Id = 735, Name = "ACIGÖL", ilId = 50},
                            new ilce() {Id = 736, Name = "AVANOS", ilId = 50},
                            new ilce() {Id = 737, Name = "DERİNKUYU", ilId = 50},
                            new ilce() {Id = 738, Name = "GÜLŞEHİR", ilId = 50},
                            new ilce() {Id = 739, Name = "HACIBEKTAŞ", ilId = 50},
                            new ilce() {Id = 740, Name = "KOZAKLI", ilId = 50},
                            new ilce() {Id = 741, Name = "MERKEZ", ilId = 50},
                            new ilce() {Id = 742, Name = "ÜRGÜP", ilId = 50},
                            new ilce() {Id = 743, Name = "ALTUNHİSAR", ilId = 51},
                            new ilce() {Id = 744, Name = "BOR", ilId = 51},
                            new ilce() {Id = 745, Name = "ÇAMARDI", ilId = 51},
                            new ilce() {Id = 746, Name = "ÇİFTLİK", ilId = 51},
                            new ilce() {Id = 747, Name = "MERKEZ", ilId = 51},
                            new ilce() {Id = 748, Name = "ULUKIŞLA", ilId = 51},
                            new ilce() {Id = 749, Name = "AKKUŞ", ilId = 52},
                            new ilce() {Id = 750, Name = "ALTINORDU", ilId = 52},
                            new ilce() {Id = 751, Name = "AYBASTI", ilId = 52},
                            new ilce() {Id = 752, Name = "ÇAMAŞ", ilId = 52},
                            new ilce() {Id = 753, Name = "ÇATALPINAR", ilId = 52},
                            new ilce() {Id = 754, Name = "ÇAYBAŞI", ilId = 52},
                            new ilce() {Id = 755, Name = "FATSA", ilId = 52},
                            new ilce() {Id = 756, Name = "GÖLKÖY", ilId = 52},
                            new ilce() {Id = 757, Name = "GÜLYALI", ilId = 52},
                            new ilce() {Id = 758, Name = "GÜRGENTEPE", ilId = 52},
                            new ilce() {Id = 759, Name = "İKİZCE", ilId = 52},
                            new ilce() {Id = 760, Name = "KABADÜZ", ilId = 52},
                            new ilce() {Id = 761, Name = "KABATAŞ", ilId = 52},
                            new ilce() {Id = 762, Name = "KORGAN", ilId = 52},
                            new ilce() {Id = 763, Name = "KUMRU", ilId = 52},
                            new ilce() {Id = 764, Name = "MESUDİYE", ilId = 52},
                            new ilce() {Id = 765, Name = "PERŞEMBE", ilId = 52},
                            new ilce() {Id = 766, Name = "ULUBEY", ilId = 52},
                            new ilce() {Id = 767, Name = "ÜNYE", ilId = 52},
                            new ilce() {Id = 768, Name = "BAHÇE", ilId = 80},
                            new ilce() {Id = 769, Name = "DÜZİÇİ", ilId = 80},
                            new ilce() {Id = 770, Name = "HASANBEYLİ", ilId = 80},
                            new ilce() {Id = 771, Name = "KADİRLİ", ilId = 80},
                            new ilce() {Id = 772, Name = "MERKEZ", ilId = 80},
                            new ilce() {Id = 773, Name = "SUMBAS", ilId = 80},
                            new ilce() {Id = 774, Name = "TOPRAKKALE", ilId = 80},
                            new ilce() {Id = 775, Name = "ARDEŞEN", ilId = 53},
                            new ilce() {Id = 776, Name = "ÇAMLIHEMŞİN", ilId = 53},
                            new ilce() {Id = 777, Name = "ÇAYELİ", ilId = 53},
                            new ilce() {Id = 778, Name = "DEREPAZARI", ilId = 53},
                            new ilce() {Id = 779, Name = "FINDIKLI", ilId = 53},
                            new ilce() {Id = 780, Name = "GÜNEYSU", ilId = 53},
                            new ilce() {Id = 781, Name = "HEMŞİN", ilId = 53},
                            new ilce() {Id = 782, Name = "İKİZDERE", ilId = 53},
                            new ilce() {Id = 783, Name = "İYİDERE", ilId = 53},
                            new ilce() {Id = 784, Name = "KALKANDERE", ilId = 53},
                            new ilce() {Id = 785, Name = "MERKEZ", ilId = 53},
                            new ilce() {Id = 786, Name = "PAZAR", ilId = 53},
                            new ilce() {Id = 787, Name = "ADAPAZARI", ilId = 54},
                            new ilce() {Id = 788, Name = "AKYAZI", ilId = 54},
                            new ilce() {Id = 789, Name = "ARİFİYE", ilId = 54},
                            new ilce() {Id = 790, Name = "ERENLER", ilId = 54},
                            new ilce() {Id = 791, Name = "FERİZLİ", ilId = 54},
                            new ilce() {Id = 792, Name = "GEYVE", ilId = 54},
                            new ilce() {Id = 793, Name = "HENDEK", ilId = 54},
                            new ilce() {Id = 794, Name = "KARAPÜRÇEK", ilId = 54},
                            new ilce() {Id = 795, Name = "KARASU", ilId = 54},
                            new ilce() {Id = 796, Name = "KAYNARCA", ilId = 54},
                            new ilce() {Id = 797, Name = "KOCAALİ", ilId = 54},
                            new ilce() {Id = 798, Name = "PAMUKOVA", ilId = 54},
                            new ilce() {Id = 799, Name = "SAPANCA", ilId = 54},
                            new ilce() {Id = 800, Name = "SERDİVAN", ilId = 54},
                            new ilce() {Id = 801, Name = "SÖĞÜTLÜ", ilId = 54},
                            new ilce() {Id = 802, Name = "TARAKLI", ilId = 54},
                            new ilce() {Id = 803, Name = "19 MAYIS", ilId = 55},
                            new ilce() {Id = 804, Name = "ALAÇAM", ilId = 55},
                            new ilce() {Id = 805, Name = "ASARCIK", ilId = 55},
                            new ilce() {Id = 806, Name = "ATAKUM", ilId = 55},
                            new ilce() {Id = 807, Name = "AYVACIK", ilId = 55},
                            new ilce() {Id = 808, Name = "BAFRA", ilId = 55},
                            new ilce() {Id = 809, Name = "CANİK", ilId = 55},
                            new ilce() {Id = 810, Name = "ÇARŞAMBA", ilId = 55},
                            new ilce() {Id = 811, Name = "HAVZA", ilId = 55},
                            new ilce() {Id = 812, Name = "İLKADIM", ilId = 55},
                            new ilce() {Id = 813, Name = "KAVAK", ilId = 55},
                            new ilce() {Id = 814, Name = "LADİK", ilId = 55},
                            new ilce() {Id = 815, Name = "SALIPAZARI", ilId = 55},
                            new ilce() {Id = 816, Name = "TEKKEKÖY", ilId = 55},
                            new ilce() {Id = 817, Name = "TERME", ilId = 55},
                            new ilce() {Id = 818, Name = "VEZİRKÖPRÜ", ilId = 55},
                            new ilce() {Id = 819, Name = "YAKAKENT", ilId = 55},
                            new ilce() {Id = 820, Name = "BAYKAN", ilId = 56},
                            new ilce() {Id = 821, Name = "ERUH", ilId = 56},
                            new ilce() {Id = 822, Name = "KURTALAN", ilId = 56},
                            new ilce() {Id = 823, Name = "MERKEZ", ilId = 56},
                            new ilce() {Id = 824, Name = "PERVARİ", ilId = 56},
                            new ilce() {Id = 825, Name = "ŞİRVAN", ilId = 56},
                            new ilce() {Id = 826, Name = "TİLLO", ilId = 56},
                            new ilce() {Id = 827, Name = "AYANCIK", ilId = 57},
                            new ilce() {Id = 828, Name = "BOYABAT", ilId = 57},
                            new ilce() {Id = 829, Name = "DİKMEN", ilId = 57},
                            new ilce() {Id = 830, Name = "DURAĞAN", ilId = 57},
                            new ilce() {Id = 831, Name = "ERFELEK", ilId = 57},
                            new ilce() {Id = 832, Name = "GERZE", ilId = 57},
                            new ilce() {Id = 833, Name = "MERKEZ", ilId = 57},
                            new ilce() {Id = 834, Name = "SARAYDÜZÜ", ilId = 57},
                            new ilce() {Id = 835, Name = "TÜRKELİ", ilId = 57},
                            new ilce() {Id = 836, Name = "AKINCILAR", ilId = 58},
                            new ilce() {Id = 837, Name = "ALTINYAYLA", ilId = 58},
                            new ilce() {Id = 838, Name = "DİVRİĞİ", ilId = 58},
                            new ilce() {Id = 839, Name = "DOĞANŞAR", ilId = 58},
                            new ilce() {Id = 840, Name = "GEMEREK", ilId = 58},
                            new ilce() {Id = 841, Name = "GÖLOVA", ilId = 58},
                            new ilce() {Id = 842, Name = "GÜRÜN", ilId = 58},
                            new ilce() {Id = 843, Name = "HAFİK", ilId = 58},
                            new ilce() {Id = 844, Name = "İMRANLI", ilId = 58},
                            new ilce() {Id = 845, Name = "KANGAL", ilId = 58},
                            new ilce() {Id = 846, Name = "KOYULHİSAR", ilId = 58},
                            new ilce() {Id = 847, Name = "MERKEZ", ilId = 58},
                            new ilce() {Id = 848, Name = "SUŞEHRİ", ilId = 58},
                            new ilce() {Id = 849, Name = "ŞARKIŞLA", ilId = 58},
                            new ilce() {Id = 850, Name = "ULAŞ", ilId = 58},
                            new ilce() {Id = 851, Name = "YILDIZELİ", ilId = 58},
                            new ilce() {Id = 852, Name = "ZARA", ilId = 58},
                            new ilce() {Id = 853, Name = "AKÇAKALE", ilId = 63},
                            new ilce() {Id = 854, Name = "BİRECİK", ilId = 63},
                            new ilce() {Id = 855, Name = "BOZOVA", ilId = 63},
                            new ilce() {Id = 856, Name = "CEYLANPINAR", ilId = 63},
                            new ilce() {Id = 857, Name = "EYYÜBİYE", ilId = 63},
                            new ilce() {Id = 858, Name = "HALFETİ", ilId = 63},
                            new ilce() {Id = 859, Name = "HALİLİYE", ilId = 63},
                            new ilce() {Id = 860, Name = "HARRAN", ilId = 63},
                            new ilce() {Id = 861, Name = "HİLVAN", ilId = 63},
                            new ilce() {Id = 862, Name = "KARAKÖPRÜ", ilId = 63},
                            new ilce() {Id = 863, Name = "SİVEREK", ilId = 63},
                            new ilce() {Id = 864, Name = "SURUÇ", ilId = 63},
                            new ilce() {Id = 865, Name = "VİRANŞEHİR", ilId = 63},
                            new ilce() {Id = 866, Name = "BEYTÜŞŞEBAP", ilId = 73},
                            new ilce() {Id = 867, Name = "CİZRE", ilId = 73},
                            new ilce() {Id = 868, Name = "GÜÇLÜKONAK", ilId = 73},
                            new ilce() {Id = 869, Name = "İDİL", ilId = 73},
                            new ilce() {Id = 870, Name = "MERKEZ", ilId = 73},
                            new ilce() {Id = 871, Name = "SİLOPİ", ilId = 73},
                            new ilce() {Id = 872, Name = "ULUDERE", ilId = 73},
                            new ilce() {Id = 873, Name = "ÇERKEZKÖY", ilId = 59},
                            new ilce() {Id = 874, Name = "ÇORLU", ilId = 59},
                            new ilce() {Id = 875, Name = "ERGENE", ilId = 59},
                            new ilce() {Id = 876, Name = "HAYRABOLU", ilId = 59},
                            new ilce() {Id = 877, Name = "KAPAKLI", ilId = 59},
                            new ilce() {Id = 878, Name = "MALKARA", ilId = 59},
                            new ilce() {Id = 879, Name = "MARMARAEREĞLİSİ", ilId = 59},
                            new ilce() {Id = 880, Name = "MURATLI", ilId = 59},
                            new ilce() {Id = 881, Name = "SARAY", ilId = 59},
                            new ilce() {Id = 882, Name = "SÜLEYMANPAŞA", ilId = 59},
                            new ilce() {Id = 883, Name = "ŞARKÖY", ilId = 59},
                            new ilce() {Id = 884, Name = "ALMUS", ilId = 60},
                            new ilce() {Id = 885, Name = "ARTOVA", ilId = 60},
                            new ilce() {Id = 886, Name = "BAŞÇİFTLİK", ilId = 60},
                            new ilce() {Id = 887, Name = "ERBAA", ilId = 60},
                            new ilce() {Id = 888, Name = "MERKEZ", ilId = 60},
                            new ilce() {Id = 889, Name = "NİKSAR", ilId = 60},
                            new ilce() {Id = 890, Name = "PAZAR", ilId = 60},
                            new ilce() {Id = 891, Name = "REŞADİYE", ilId = 60},
                            new ilce() {Id = 892, Name = "SULUSARAY", ilId = 60},
                            new ilce() {Id = 893, Name = "TURHAL", ilId = 60},
                            new ilce() {Id = 894, Name = "YEŞİLYURT", ilId = 60},
                            new ilce() {Id = 895, Name = "ZİLE", ilId = 60},
                            new ilce() {Id = 896, Name = "AKÇAABAT", ilId = 61},
                            new ilce() {Id = 897, Name = "ARAKLI", ilId = 61},
                            new ilce() {Id = 898, Name = "ARSİN", ilId = 61},
                            new ilce() {Id = 899, Name = "BEŞİKDÜZÜ", ilId = 61},
                            new ilce() {Id = 900, Name = "ÇARŞIBAŞI", ilId = 61},
                            new ilce() {Id = 901, Name = "ÇAYKARA", ilId = 61},
                            new ilce() {Id = 902, Name = "DERNEKPAZARI", ilId = 61},
                            new ilce() {Id = 903, Name = "DÜZKÖY", ilId = 61},
                            new ilce() {Id = 904, Name = "HAYRAT", ilId = 61},
                            new ilce() {Id = 905, Name = "KÖPRÜBAŞI", ilId = 61},
                            new ilce() {Id = 906, Name = "MAÇKA", ilId = 61},
                            new ilce() {Id = 907, Name = "OF", ilId = 61},
                            new ilce() {Id = 908, Name = "ORTAHİSAR", ilId = 61},
                            new ilce() {Id = 909, Name = "SÜRMENE", ilId = 61},
                            new ilce() {Id = 910, Name = "ŞALPAZARI", ilId = 61},
                            new ilce() {Id = 911, Name = "TONYA", ilId = 61},
                            new ilce() {Id = 912, Name = "VAKFIKEBİR", ilId = 61},
                            new ilce() {Id = 913, Name = "YOMRA", ilId = 61},
                            new ilce() {Id = 914, Name = "ÇEMİŞGEZEK", ilId = 62},
                            new ilce() {Id = 915, Name = "HOZAT", ilId = 62},
                            new ilce() {Id = 916, Name = "MAZGİRT", ilId = 62},
                            new ilce() {Id = 917, Name = "MERKEZ", ilId = 62},
                            new ilce() {Id = 918, Name = "NAZIMİYE", ilId = 62},
                            new ilce() {Id = 919, Name = "OVACIK", ilId = 62},
                            new ilce() {Id = 920, Name = "PERTEK", ilId = 62},
                            new ilce() {Id = 921, Name = "PÜLÜMÜR", ilId = 62},
                            new ilce() {Id = 922, Name = "BANAZ", ilId = 64},
                            new ilce() {Id = 923, Name = "EŞME", ilId = 64},
                            new ilce() {Id = 924, Name = "KARAHALLI", ilId = 64},
                            new ilce() {Id = 925, Name = "MERKEZ", ilId = 64},
                            new ilce() {Id = 926, Name = "SİVASLI", ilId = 64},
                            new ilce() {Id = 927, Name = "ULUBEY", ilId = 64},
                            new ilce() {Id = 928, Name = "BAHÇESARAY", ilId = 65},
                            new ilce() {Id = 929, Name = "BAŞKALE", ilId = 65},
                            new ilce() {Id = 930, Name = "ÇALDIRAN", ilId = 65},
                            new ilce() {Id = 931, Name = "ÇATAK", ilId = 65},
                            new ilce() {Id = 932, Name = "EDREMİT", ilId = 65},
                            new ilce() {Id = 933, Name = "ERCİŞ", ilId = 65},
                            new ilce() {Id = 934, Name = "GEVAŞ", ilId = 65},
                            new ilce() {Id = 935, Name = "GÜRPINAR", ilId = 65},
                            new ilce() {Id = 936, Name = "İPEKYOLU", ilId = 65},
                            new ilce() {Id = 937, Name = "MURADİYE", ilId = 65},
                            new ilce() {Id = 938, Name = "ÖZALP", ilId = 65},
                            new ilce() {Id = 939, Name = "SARAY", ilId = 65},
                            new ilce() {Id = 940, Name = "TUŞBA", ilId = 65},
                            new ilce() {Id = 941, Name = "ALTINOVA", ilId = 77},
                            new ilce() {Id = 942, Name = "ARMUTLU", ilId = 77},
                            new ilce() {Id = 943, Name = "ÇINARCIK", ilId = 77},
                            new ilce() {Id = 944, Name = "ÇİFTLİKKÖY", ilId = 77},
                            new ilce() {Id = 945, Name = "MERKEZ", ilId = 77},
                            new ilce() {Id = 946, Name = "TERMAL", ilId = 77},
                            new ilce() {Id = 947, Name = "AKDAĞMADENİ", ilId = 66},
                            new ilce() {Id = 948, Name = "AYDINCIK", ilId = 66},
                            new ilce() {Id = 949, Name = "BOĞAZLIYAN", ilId = 66},
                            new ilce() {Id = 950, Name = "ÇANDIR", ilId = 66},
                            new ilce() {Id = 951, Name = "ÇAYIRALAN", ilId = 66},
                            new ilce() {Id = 952, Name = "ÇEKEREK", ilId = 66},
                            new ilce() {Id = 953, Name = "KADIŞEHRİ", ilId = 66},
                            new ilce() {Id = 954, Name = "MERKEZ", ilId = 66},
                            new ilce() {Id = 955, Name = "SARAYKENT", ilId = 66},
                            new ilce() {Id = 956, Name = "SARIKAYA", ilId = 66},
                            new ilce() {Id = 957, Name = "SORGUN", ilId = 66},
                            new ilce() {Id = 958, Name = "ŞEFAATLİ", ilId = 66},
                            new ilce() {Id = 959, Name = "YENİFAKILI", ilId = 66},
                            new ilce() {Id = 960, Name = "YERKÖY", ilId = 66},
                            new ilce() {Id = 961, Name = "ALAPLI", ilId = 67},
                            new ilce() {Id = 962, Name = "ÇAYCUMA", ilId = 67},
                            new ilce() {Id = 963, Name = "DEVREK", ilId = 67},
                            new ilce() {Id = 964, Name = "EREĞLİ", ilId = 67},
                            new ilce() {Id = 965, Name = "GÖKÇEBEY", ilId = 67},
                            new ilce() {Id = 966, Name = "KİLİMLİ", ilId = 67},
                            new ilce() {Id = 967, Name = "KOZLU", ilId = 67},
                            new ilce() {Id = 968, Name = "MERKEZ", ilId = 67}
                        };
                    await _ilceRepository.AddRangeAsync(ilces);
                    await _unitOfWork.CommitAsync();
                }

            }
            catch (Exception ex)
            {
                // Log any exceptions that occur during the seeding process
                Console.WriteLine(ex.Message);
            }
        }
        public async Task SeedWorksiteWorkerTypesAsync()
        {
            try
            {
                if ((await _WorksiteWorkerTypeRepository.GetAllAsync()).Count == 0)
                {
                    var worksiteWorkerType = new WorksiteWorkerType() { Name = "Worker",OvertimeWage = 15 };
                    await _WorksiteWorkerTypeRepository.AddAsync(worksiteWorkerType);

                    var worksiteWorkerType2 = new WorksiteWorkerType() { Name = "Forman", OvertimeWage = 30 };
                    await _WorksiteWorkerTypeRepository.AddAsync(worksiteWorkerType2);


                    await _unitOfWork.CommitAsync();
                }

            }
            catch (Exception ex)
            {
                // Log any exceptions that occur during the seeding process
                Console.WriteLine(ex.Message);
            }
        }
        public async Task SeedWorksiteActionTypesAsync()
        {
            try
            {
                if ((await _WorksiteActionTypeRepository.GetAllAsync()).Count == 0)
                {
                    var worksiteActionType = new WorksiteActionType() { Id = 1, Name = "Excavation Process" };
                    await _WorksiteActionTypeRepository.AddAsync(worksiteActionType);

                    var worksiteActionType2 = new WorksiteActionType() { Id = 2, Name = "Other" };
                    await _WorksiteActionTypeRepository.AddAsync(worksiteActionType2);


                    await _unitOfWork.CommitAsync();
                }

            }
            catch (Exception ex)
            {
                // Log any exceptions that occur during the seeding process
                Console.WriteLine(ex.Message);
            }
        }
        public async Task SeedYearMonthAsync()
        {
            try
            {
                if ((await _YearRepository.GetAllAsync()).Count == 0)
                {
                    for (int i = 2020; i <= 2050; i++)
                    {
                        var year = new Year() { Id = i };
                        await _YearRepository.AddAsync(year);
                    }  
                    await _unitOfWork.CommitAsync();
                }
                if ((await _YearRepository.GetAllAsync()).Count == 0)
                {
                    for (int i = 1; i <= 12; i++)
                    {
                        var month1 = new Month() { Id = i,
                            Name = i switch
                            {
                                1 => "January",
                                2 => "February",
                                3 => "March",
                                4 => "April",
                                5 => "May",
                                6 => "June",
                                7 => "July",
                                8 => "August",
                                9 => "September",
                                10 => "October",
                                11 => "November",
                                12 => "December",
                                _ => "Unknown" // default case if i is not in the range 1-12
                            }
                        };
                        await _MonthRepository.AddAsync(month1);
                    }
                    await _unitOfWork.CommitAsync();
                }
            }
            catch (Exception ex)
            {
                // Log any exceptions that occur during the seeding process
                Console.WriteLine(ex.Message);
            }
        }
    }
}
